<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4kzNVlv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4kzNVlv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4kzNVlv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4kzNVlv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4kzNVlv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4kzNVlv',
    'container.build_id' => 'bdb0c932',
    'container.build_time' => 1646841480,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4kzNVlv');
